### ISSUE TITLE
Few issues with latest version

### ISSUE THREAD

**Issue by Profforgr** [alibaba/tengine#644]
Hi.

I am using older version of tengine (before 1.8.0 = 1.7.12) merge.

I'm testing latest git master and detected the following issues which most probably comes after 1.8.0 = 1.7.12 merge. Just want to report them.

1 
```nginx
./configure
...
checking for getaddrinfo() ... found
./configure: 703: [: =: unexpected operator
checking for PCRE library ... found
...
```

I think it may be important, but i can not detect where issue is.

2 Tengine is not compileable with backtrace-module.

```c++
./configure --with-backtrace_module
make
...
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs -I src/http -I src/http/modules -I src/mail \
                -o objs/src/misc/ngx_backtrace_module.o \
                src/misc/ngx_backtrace_module.c
src/misc/ngx_backtrace_module.c:29:1: error: unknown type name ‘ngx_signal_t’
src/misc/ngx_backtrace_module.c:30:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: (near initialization for ‘ngx_backtrace_signals[0]’) [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: (near initialization for ‘ngx_backtrace_signals[0]’) [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: (near initialization for ‘ngx_backtrace_signals[0]’) [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:30:5: error: (near initialization for ‘ngx_backtrace_signals[0]’) [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: (near initialization for ‘ngx_backtrace_signals[1]’) [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: (near initialization for ‘ngx_backtrace_signals[1]’) [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: (near initialization for ‘ngx_backtrace_signals[1]’) [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:33:5: error: (near initialization for ‘ngx_backtrace_signals[1]’) [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: (near initialization for ‘ngx_backtrace_signals[2]’) [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: (near initialization for ‘ngx_backtrace_signals[2]’) [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: (near initialization for ‘ngx_backtrace_signals[2]’) [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:36:5: error: (near initialization for ‘ngx_backtrace_signals[2]’) [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: (near initialization for ‘ngx_backtrace_signals[3]’) [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: (near initialization for ‘ngx_backtrace_signals[3]’) [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: (near initialization for ‘ngx_backtrace_signals[3]’) [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:38:5: error: (near initialization for ‘ngx_backtrace_signals[3]’) [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: (near initialization for ‘ngx_backtrace_signals[4]’) [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: (near initialization for ‘ngx_backtrace_signals[4]’) [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: (near initialization for ‘ngx_backtrace_signals[4]’) [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:40:5: error: (near initialization for ‘ngx_backtrace_signals[4]’) [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: (near initialization for ‘ngx_backtrace_signals[5]’) [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: (near initialization for ‘ngx_backtrace_signals[5]’) [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: (near initialization for ‘ngx_backtrace_signals[5]’) [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:42:5: error: (near initialization for ‘ngx_backtrace_signals[5]’) [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: braces around scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: (near initialization for ‘ngx_backtrace_signals[6]’) [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: (near initialization for ‘ngx_backtrace_signals[6]’) [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: (near initialization for ‘ngx_backtrace_signals[6]’) [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: excess elements in scalar initializer [-Werror]
src/misc/ngx_backtrace_module.c:44:5: error: (near initialization for ‘ngx_backtrace_signals[6]’) [-Werror]
src/misc/ngx_backtrace_module.c: In function ‘ngx_init_error_signals’:
src/misc/ngx_backtrace_module.c:94:5: error: unknown type name ‘ngx_signal_t’
src/misc/ngx_backtrace_module.c:97:42: error: request for member ‘signo’ in something not a structure or union
src/misc/ngx_backtrace_module.c:99:28: error: request for member ‘handler’ in something not a structure or union
src/misc/ngx_backtrace_module.c:101:26: error: request for member ‘signo’ in something not a structure or union
src/misc/ngx_backtrace_module.c:102:13: error: request for member ‘signame’ in something not a structure or union
src/misc/ngx_backtrace_module.c: In function ‘ngx_error_signal_handler’:
src/misc/ngx_backtrace_module.c:118:5: error: unknown type name ‘ngx_signal_t’
src/misc/ngx_backtrace_module.c:122:42: error: request for member ‘signo’ in something not a structure or union
src/misc/ngx_backtrace_module.c:123:16: error: request for member ‘signo’ in something not a structure or union
src/misc/ngx_backtrace_module.c:132:5: error: request for member ‘signame’ in something not a structure or union
src/misc/ngx_backtrace_module.c:139:9: error: request for member ‘signame’ in something not a structure or union
cc1: all warnings being treated as errors
make[1]: *** [objs/src/misc/ngx_backtrace_module.o] Error 1
make: *** [build] Error 2
```

Include it as an external module does not work either.

```c
../modules/nginx-backtrace/ngx_backtrace_module.c: In function ‘ngx_backtrace_files’:
../modules/nginx-backtrace/ngx_backtrace_module.c:187:5: error: implicit declaration of function ‘ngx_log_create’ [-Werror=implicit-function-declaration]
../modules/nginx-backtrace/ngx_backtrace_module.c:187:9: error: assignment makes pointer from integer without a cast [-Werror]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-backtrace/ngx_backtrace_module.o] Error 1
make: *** [build] Error 2
```

3 log_empty_request directive disappeared.

```nginx
[emerg] unknown directive "log_empty_request"
```

**Comment by chobits** [comment]
Thanks for the report. I pull a request to fix the first issue, see https://github.com/alibaba/tengine/pull/645.

**Comment by chobits** [comment]
Another fix for second issue is here: #646.

**Comment by Profforgr** [comment]
> Another fix for second issue is here: #646.

Thanks. Any news about log_empty_request ?

**Comment by Frodox** [comment]
Upd, any news about `ngx_log_create` ? trying to build with nginx-1.14
